### ISSUE TITLE
Request settings in app-config.yaml

### ISSUE THREAD

**Issue by ruieloi** [vippsas/backstage-azure-resources-backend#1]
Hi.

I would want to request we can set the Azure variables in the app-config.yaml file since we already use these values in diff environment variables.

Example:

`
azureResources:
  clientId: $(AZURE_CLIENT_ID)
  clientSecret: $(AZURE_CLIENT_SECRET)
  tenantId: $(AZURE_TENANT_ID)
`

Thanks

**Comment by ehrnst** [comment]
Hi. Sorry for the late reply. I agree. this should be fixed as soon as possible. I forgot to do it initially since we host on azure and use managed identity.
Did you manage to configure it using environment variables without the config file?

**Comment by ruieloi** [comment]
Hi, yes we did but now we have multiple Environment Variables for the same values which is messy!
Thanks

**Comment by ehrnst** [comment]
We fixed this in the latest release :)

**Comment by ruieloi** [comment]
Thanks! Will test when I've some time.
